# Generated by Django 3.0.7 on 2020-07-06 19:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_reminder_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 6, 23, 37, 58, 409630)),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 6, 23, 37, 58, 394003)),
        ),
    ]
