# Generated by Django 3.0.7 on 2020-07-06 19:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_manager', '0002_auto_20200706_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_time',
            field=models.CharField(default='00:00', max_length=8),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_reminder_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 6, 23, 49, 56, 214695)),
        ),
    ]
